const data = [
  [ // row 1 en
    { key: '`' },
    { key: '1' },
    { key: '2' },
    { key: '3' },
    { key: '4' },
    { key: '5' },
    { key: '6' },
    { key: '7' },
    { key: '8' },
    { key: '9' },
    { key: '0' },
    { key: '-' },
    { key: '=' },
    { key: 'backspace' },
  ],
  [ // row 2 en
    { key: 'tab' },
    { key: 'q' },
    { key: 'w' },
    { key: 'e' },
    { key: 'r' },
    { key: 't' },
    { key: 'y' },
    { key: 'u' },
    { key: 'i' },
    { key: 'o' },
    { key: 'p' },
    { key: '[' },
    { key: ']' },
    { key: '\\' },
  ],
  [// row 3 en
    { key: 'capslock' },
    { key: 'a' },
    { key: 's' },
    { key: 'd' },
    { key: 'f' },
    { key: 'g' },
    { key: 'h' },
    { key: 'j' },
    { key: 'k' },
    { key: 'l' },
    { key: ';' },
    { key: '\'' },
    { key: 'enter' },
  ],
  [// row 4 en
    { key: 'shift' },
    { key: 'z' },
    { key: 'x' },
    { key: 'c' },
    { key: 'v' },
    { key: 'b' },
    { key: 'n' },
    { key: 'm' },
    { key: ',' },
    { key: '.' },
    { key: '/' },
    { key: '▲' },
    { key: 'shift' },
  ],
  [ // row 5 en
    { key: 'ctrl' },
    { key: 'win' },
    { key: 'alt' },
    { key: 'space' },
    { key: 'alt' },
    { key: 'ctrl' },
    { key: '◄' },
    { key: '▼' },
    { key: '►' },
  ],
];

export default data;
