const dataRu = [
  [ // row 1 ru
    { key: 'ё', caps: 'Ё', code: 'Backquote' },
    { key: '1', caps: '!', code: 'Digit1' },
    { key: '2', caps: '"', code: 'Digit2' },
    { key: '3', caps: '№', code: 'Digit3' },
    { key: '4', caps: ';', code: 'Digit4' },
    { key: '5', caps: '%', code: 'Digit5' },
    { key: '6', caps: ':', code: 'Digit6' },
    { key: '7', caps: '?', code: 'Digit7' },
    { key: '8', caps: '*', code: 'Digit8' },
    { key: '9', caps: '(', code: 'Digit9' },
    { key: '0', caps: ')', code: 'Digit0' },
    { key: '-', caps: '_', code: 'Minus' },
    { key: '=', caps: '+', code: 'Equal' },
    { key: 'backspace', caps: 'backspace', code: 'Backspace' },
  ],
  [ // row 2 en
    { key: 'tab', caps: 'tab', code: 'Tab' },
    { key: 'й', caps: 'Й', code: 'KeyQ' },
    { key: 'ц', caps: 'Ц', code: 'KeyW' },
    { key: 'у', caps: 'У', code: 'KeyE' },
    { key: 'к', caps: 'К', code: 'KeyR' },
    { key: 'е', caps: 'Е', code: 'KeyT' },
    { key: 'н', caps: 'Н', code: 'KeyY' },
    { key: 'г', caps: 'Г', code: 'KeyU' },
    { key: 'ш', caps: 'Ш', code: 'KeyI' },
    { key: 'щ', caps: 'Щ', code: 'KeyO' },
    { key: 'з', caps: 'З', code: 'KeyP' },
    { key: 'х', caps: 'Х', code: 'BracketLeft' },
    { key: 'ъ', caps: 'Ъ', code: 'BracketRight' },
    { key: '\\', caps: '/', code: 'Backslash' },
  ],
  [// row 3 en
    { key: 'capslock', caps: 'capslock', code: 'CapsLock' },
    { key: 'ф', caps: 'Ф', code: 'KeyA' },
    { key: 'ы', caps: 'Ы', code: 'KeyS' },
    { key: 'в', caps: 'В', code: 'KeyD' },
    { key: 'а', caps: 'А', code: 'KeyF' },
    { key: 'п', caps: 'П', code: 'KeyG' },
    { key: 'р', caps: 'Р', code: 'KeyH' },
    { key: 'о', caps: 'О', code: 'KeyJ' },
    { key: 'л', caps: 'Л', code: 'KeyK' },
    { key: 'д', caps: 'Д', code: 'KeyL' },
    { key: 'ж', caps: 'Ж', code: 'Semicolon' },
    { key: 'э', caps: 'Э', code: 'Quote' },
    { key: 'enter', caps: 'enter', code: 'Enter' },
  ],
  [// row 4 en
    { key: 'shift', caps: 'shift', code: 'ShiftLeft' },
    { key: 'я', caps: 'Я', code: 'KeyZ' },
    { key: 'ч', caps: 'Ч', code: 'KeyX' },
    { key: 'с', caps: 'С', code: 'KeyC' },
    { key: 'м', caps: 'М', code: 'KeyV' },
    { key: 'и', caps: 'И', code: 'KeyB' },
    { key: 'т', caps: 'Т', code: 'KeyN' },
    { key: 'ь', caps: 'Ь', code: 'KeyM' },
    { key: 'б', caps: 'Б', code: 'Comma' },
    { key: 'ю', caps: 'Ю', code: 'Period' },
    { key: '.', caps: ',', code: 'Slash' },
    { key: '▲', caps: '▲', code: 'ArrowUp' },
    { key: 'shift', caps: 'shift', code: 'ShiftRight' },
  ],
  [ // row 5 en
    { key: 'ctrl', caps: 'ctrl', code: 'ControlLeft' },
    { key: 'alt', caps: 'alt', code: 'AltLeft' },
    { key: 'space', caps: 'space', code: 'Space' },
    { key: 'alt', caps: 'alt', code: 'AltRight' },
    { key: 'ctrl', caps: 'ctrl', code: 'ControlRight' },
    { key: '◄', caps: '◄', code: 'ArrowLeft' },
    { key: '▼', caps: '▼', code: 'ArrowDown' },
    { key: '►', caps: '►', code: 'ArrowRight' },
    { key: 'ru', caps: 'ru', code: 'lang' },
  ],
];

export default dataRu;
