const dataEn = [
  [ // row 1 en
    { key: '`', code: 'Backquote' },
    { key: '1', code: 'Digit1' },
    { key: '2', code: 'Digit2' },
    { key: '3', code: 'Digit3' },
    { key: '4', code: 'Digit4' },
    { key: '5', code: 'Digit5' },
    { key: '6', code: 'Digit6' },
    { key: '7', code: 'Digit7' },
    { key: '8', code: 'Digit8' },
    { key: '9', code: 'Digit9' },
    { key: '0', code: 'Digit0' },
    { key: '-', code: 'Minus' },
    { key: '=', code: 'Equal' },
    { key: 'backspace', code: 'Backspace' },
  ],
  [ // row 2 en
    { key: 'tab', code: 'Tab' },
    { key: 'q', code: 'KeyQ' },
    { key: 'w', code: 'KeyW' },
    { key: 'e', code: 'KeyE' },
    { key: 'r', code: 'KeyR' },
    { key: 't', code: 'KeyT' },
    { key: 'y', code: 'KeyY' },
    { key: 'u', code: 'KeyU' },
    { key: 'i', code: 'KeyI' },
    { key: 'o', code: 'KeyO' },
    { key: 'p', code: 'KeyP' },
    { key: '[', code: 'BracketLeft' },
    { key: ']', code: 'BracketRight' },
    { key: '\\', code: 'Backslash' },
  ],
  [// row 3 en
    { key: 'capslock', code: 'CapsLock' },
    { key: 'a', code: 'KeyA' },
    { key: 's', code: 'KeyS' },
    { key: 'd', code: 'KeyD' },
    { key: 'f', code: 'KeyF' },
    { key: 'g', code: 'KeyG' },
    { key: 'h', code: 'KeyH' },
    { key: 'j', code: 'KeyJ' },
    { key: 'k', code: 'KeyK' },
    { key: 'l', code: 'KeyL' },
    { key: ';', code: 'Semicolon' },
    { key: '\'', code: 'Quote' },
    { key: 'enter', code: 'Enter' },
  ],
  [// row 4 en
    { key: 'shift', code: 'ShiftLeft' },
    { key: 'z', code: 'KeyZ' },
    { key: 'x', code: 'KeyX' },
    { key: 'c', code: 'KeyC' },
    { key: 'v', code: 'KeyV' },
    { key: 'b', code: 'KeyB' },
    { key: 'n', code: 'KeyN' },
    { key: 'm', code: 'KeyM' },
    { key: ',', code: 'Comma' },
    { key: '.', code: 'Period' },
    { key: '/', code: 'Slash' },
    { key: '▲', code: 'ArrowUp' },
    { key: 'shift', code: 'ShiftRight' },
  ],
  [ // row 5 en
    { key: 'ctrl', code: 'ControlLeft' },
    { key: 'alt', code: 'AltLeft' },
    { key: 'space', code: 'Space' },
    { key: 'alt', code: 'AltRight' },
    { key: 'ctrl', code: 'ControlRight' },
    { key: '◄', code: 'ArrowLeft' },
    { key: '▼', code: 'ArrowDown' },
    { key: '►', code: 'ArrowRight' },
    { key: 'eng', code: 'lang' },
  ],
];

export default dataEn;
