const dataEn = [
  [ // row 1 en
    { key: '`', caps: '~', code: 'Backquote' },
    { key: '1', caps: '!', code: 'Digit1' },
    { key: '2', caps: '@', code: 'Digit2' },
    { key: '3', caps: '#', code: 'Digit3' },
    { key: '4', caps: '$', code: 'Digit4' },
    { key: '5', caps: '%', code: 'Digit5' },
    { key: '6', caps: '^', code: 'Digit6' },
    { key: '7', caps: '&', code: 'Digit7' },
    { key: '8', caps: '*', code: 'Digit8' },
    { key: '9', caps: '(', code: 'Digit9' },
    { key: '0', caps: ')', code: 'Digit0' },
    { key: '-', caps: '_', code: 'Minus' },
    { key: '=', caps: '+', code: 'Equal' },
    { key: 'backspace', caps: 'backspace', code: 'Backspace' },
  ],
  [ // row 2 en
    { key: 'tab', caps: 'tab', code: 'Tab' },
    { key: 'q', caps: 'Q', code: 'KeyQ' },
    { key: 'w', caps: 'W', code: 'KeyW' },
    { key: 'e', caps: 'E', code: 'KeyE' },
    { key: 'r', caps: 'R', code: 'KeyR' },
    { key: 't', caps: 'T', code: 'KeyT' },
    { key: 'y', caps: 'Y', code: 'KeyY' },
    { key: 'u', caps: 'U', code: 'KeyU' },
    { key: 'i', caps: 'I', code: 'KeyI' },
    { key: 'o', caps: 'O', code: 'KeyO' },
    { key: 'p', caps: 'P', code: 'KeyP' },
    { key: '[', caps: '{', code: 'BracketLeft' },
    { key: ']', caps: '}', code: 'BracketRight' },
    { key: '\\', caps: '|', code: 'Backslash' },
  ],
  [// row 3 en
    { key: 'capslock', caps: 'capslock', code: 'CapsLock' },
    { key: 'a', caps: 'A', code: 'KeyA' },
    { key: 's', caps: 'S', code: 'KeyS' },
    { key: 'd', caps: 'D', code: 'KeyD' },
    { key: 'f', caps: 'F', code: 'KeyF' },
    { key: 'g', caps: 'G', code: 'KeyG' },
    { key: 'h', caps: 'H', code: 'KeyH' },
    { key: 'j', caps: 'J', code: 'KeyJ' },
    { key: 'k', caps: 'K', code: 'KeyK' },
    { key: 'l', caps: 'L', code: 'KeyL' },
    { key: ';', caps: ':', code: 'Semicolon' },
    { key: '\'', caps: '"', code: 'Quote' },
    { key: 'enter', caps: 'enter', code: 'Enter' },
  ],
  [// row 4 en
    { key: 'shift', caps: 'shift', code: 'ShiftLeft' },
    { key: 'z', caps: 'Z', code: 'KeyZ' },
    { key: 'x', caps: 'X', code: 'KeyX' },
    { key: 'c', caps: 'C', code: 'KeyC' },
    { key: 'v', caps: 'V', code: 'KeyV' },
    { key: 'b', caps: 'B', code: 'KeyB' },
    { key: 'n', caps: 'N', code: 'KeyN' },
    { key: 'm', caps: 'M', code: 'KeyM' },
    { key: ',', caps: '<', code: 'Comma' },
    { key: '.', caps: '>', code: 'Period' },
    { key: '/', caps: '?', code: 'Slash' },
    { key: '▲', caps: '▲', code: 'ArrowUp' },
    { key: 'shift', caps: 'shift', code: 'ShiftRight' },
  ],
  [ // row 5 en
    { key: 'ctrl', caps: 'ctrl', code: 'ControlLeft' },
    { key: 'alt', caps: 'alt', code: 'AltLeft' },
    { key: 'space', caps: 'space', code: 'Space' },
    { key: 'alt', caps: 'alt', code: 'AltRight' },
    { key: 'ctrl', caps: 'ctrl', code: 'ControlRight' },
    { key: '◄', caps: '◄', code: 'ArrowLeft' },
    { key: '▼', caps: '▼', code: 'ArrowDown' },
    { key: '►', caps: '►', code: 'ArrowRight' },
    { key: 'eng', caps: 'eng', code: 'lang' },
  ],
];

export default dataEn;
